"""Emit tool/carriers.js — the carrier reference (roster + AM Best assessment labels).

This is the project's OWN research (roster identities + public assessment labels), not licensed
S&P data, so it is safe to embed in the published tool. The in-browser Input tab uses it to (a)
match a dropped S&P pull to a carrier by lead-entity / rating-unit name and (b) attach the Y labels
+ rating_basis so notching works client-side. Financials are never embedded — they come only from
the files the analyst drops in.

Regenerate: python src/emit_ref_js.py   (after editing the roster or assessments)
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROSTER = ROOT / "data" / "carriers_seed.csv"
ASSESS = ROOT / "data" / "assessments.csv"
OUT = ROOT / "tool" / "carriers.js"


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", (s or "").lower())


def main():
    roster = {r["rating_unit_name"]: r for r in csv.DictReader(ROSTER.open())}
    assess = {r["rating_unit_name"]: r for r in csv.DictReader(ASSESS.open())}
    out = []
    for name, ro in roster.items():
        a = assess.get(name, {})
        out.append({
            "rating_unit_name": name,
            "lead_entity": ro.get("lead_entity", ""),
            "stratum": ro.get("stratum", ""),
            "ownership": ro.get("ownership", ""),
            "fsr": a.get("fsr", ""), "icr": a.get("icr", ""),
            "outlook": a.get("outlook", ""), "under_review": a.get("under_review", ""),
            "bs_assessment": a.get("bs_assessment", ""), "op_assessment": a.get("op_assessment", ""),
            "bp_assessment": a.get("bp_assessment", ""), "erm_assessment": a.get("erm_assessment", ""),
            "rating_basis": a.get("rating_basis", "standalone"),
            "rating_action_date": a.get("rating_action_date", ""),
            "source_url": a.get("source_url", ""),
        })
    OUT.write_text("// Generated by src/emit_ref_js.py — roster + AM Best labels (no S&P financials).\n"
                   "window.CARRIER_REF = " + json.dumps(out, indent=1) + ";\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(out)} carriers, "
          f"{sum(1 for r in out if r['bs_assessment'])} with assessments)")


if __name__ == "__main__":
    main()
